# Generated by Django 5.2.3 on 2025-06-25 19:23

import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=exams.models.exam_file_path),
        ),
    ]
