# Generated by Django 5.2.3 on 2025-06-25 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='crisis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
