# Generated by Django 5.2.3 on 2025-06-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0002_crisis_created_at_crisis_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisis',
            name='user',
        ),
    ]
